# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: s3-pgp-encryptor

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"
  environment:
    base64encodedpublickey: LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptUUVOQkZyOXBJa0JDQURHK3drWWZkUCtRa0pUbllGWDNOT3VQL1dIbmNlQVZjRXo5Znc4VDZ5YmYrdEk2K0lDClBONG9RaTFBTXpHYzd0S0lQZ2FiRWdQbWk3N2NiSXFjTlY1RkZHN1NQN1ltS29KWlc1aUEvTFNFZFpFRzI2c1EKTHdjZ3hadnY4djBBWFRHYU1TYlA3WG1YalJ2YWdKNEtBK2V3bksvYW1IeVdhL2V1TXFqTEc3Z2JoNzFvZVpqZQpYR3BCZ3lIK1hETmJEWkJiUEtMTHk0WVJkOHNsMDZYWWZFSlpYNzNhZDliUDQvWlBUMkNUU25DVklNbWw2bFl0Ck8xYkFQSFZya0FqeWM2NTkvV0FESUhyMWZJcUwydlFrY3ZHTjhtM2h3R2REenpyTll4YXpSQ1JKL1gySElNLzIKQVNpcnBKMmxvTUNjZ3hJVis2d2tQbjFNcWtNUHFLYWFMeVVQQUJFQkFBRzBIVVJoYmlCTVlXMWlJRHhzWVcxaQpMbVJoYmtCbmJXRnBiQzVqYjIwK2lRRlVCQk1CQ0FBK0ZpRUVDQWl4U1VGZWtQV1FyZEZyWnM4WURhSjcrbDRGCkFscjlwSWtDR3dNRkNRUENad0FGQ3drSUJ3SUdGUW9KQ0FzQ0JCWUNBd0VDSGdFQ0Y0QUFDZ2tRWnM4WURhSjcKK2w0VjdRZi9ZeWgyNXB5cUlPVGVnZUIySkdZMGhja09ocDNFazNaamNiL1NGWVlCalVoM3k0T1VxMEZTeTJHbwpXaU1Ic0VqNXpyNTJpUGRwQlhIclI4MjdJOFNLbGg3TWdWaC9vbUx5dWtVRjlzN2N0bFlFMzh5RitJeEFLeDMrCk1mUTg2MFpZS2lQQVBhSWVFcEZZQ1ZFNEdLOVJuN0RqRGVybTBqdXorYSs5cnRXaDAwWHN1SzFxL3M1WFFyODUKNFJpOHdkVnJYMG02WldxdWxWUkZXMnQ3UDhtUmFlRk4vMVZWY3FRUVhJRzZUUlNqa2R6eDBwWTZKZkNpOXY4RwpNR2RJVzdpWCtROHdGc0lVSW5yV0MrcjRIUllqUVp2Zi9XcHdlano5b1o4MXlKRm11NkQ4RXpVVlg2YkVkbzNGCnZQU2kra2Z0MnpjbDU5d2JyUkxNb3JzanpJbXBNTGtCRFFSYS9hU0pBUWdBMDEzRVhoaWt6THZNS2ZwR2hYRi8KVzI3ZG1xMmJCQXh2UWRRdE1PaU5pUEdWSzFOR2JmRy9qMmkwMHZkb3pVbHBzMmJYWjAydERZV3NzWU9iSWY0TgpJR0puWSswMUlPOVJwVDhuWi83R2xZeVN4R2UvN2xWYnNWV256bThsR1FVYXhaS2svODBxR0JiSG5XUnZ1NGQ2ClhWc0tkNmdNL3Bkc0tIWDRqRFJYM2l2Y0M4OFV5N2lsT090UDVOenBpYzBLUC9VTVBRZFUyNVhUR0M2cjFWb0oKdkdIckxNV3JzVHpVMS83TW1wTVVDNnZ1VS9aWlhsZGt6bWtxa1RZZUZLSm9pTXN2NXVHY0thMHp1N3Z1K2ZWKwo4eExKTy9qdFNoRytKK3hVdWdOSHJvNGtTeEFxMVZCd2d0RHdMT1I4NHRoM3p1M01oL20xMjlVU0JZMWh5ZnVBCk5RQVJBUUFCaVFFOEJCZ0JDQUFtRmlFRUNBaXhTVUZla1BXUXJkRnJaczhZRGFKNytsNEZBbHI5cElrQ0d3d0YKQ1FQQ1p3QUFDZ2tRWnM4WURhSjcrbDZLYUFmL1lVQWhqK2lOMDRNWCtxcVhiZExpb1I5emZnelNTTk5iVnJ6RApzVTYvSWE5STNFMEszdHpVa1BMelRuQ0pCcHJsWlkwdE5uWUF5NHJvOFdhR3FuYW4wTkVXaUNEeFhhZ1JudWdGCk9EVlpJV1FHNWh2cDM4WlFldHpWcWtpSkc1SWpGVkhpejlaOHlHUjRNckxiT2RUeG5kNGZsdlhxYVMrZTZ6dWwKd0RiUDRHN1dmTHBDY2w0bW1ZU0dyMWx6T21uY0Q5TnZ0b3J5S0Y2WDJNbk9rbTh4YTRVVlVqbXBHb2xOclgwVgoxaVh3bk1JZ2hKb0cvRXE4MUZ3SVM4cWpIRm1XaTk3TjlDUlppNGFIMGliMnNiaHpnSzhKSnhWb2Z1MVhkNHJjClRkeVhWcWhzaXdaa1BaTUJDTkhGY0dZMnFZZE9aSGU2VXlEQ21sVkRqQzBZQ2dNWklnPT0KPXR1NUkKLS0tLS1FTkQgUEdQIFBVQkxJQyBLRVkgQkxPQ0stLS0tLQo=

# The `functions` block defines what code to deploy
functions:
  encrypt:
    handler: handler.encrypt
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - s3:
          bucket: s3-pgp-encryptor-demo-bucket
          event: s3:ObjectCreated:*
